### ISSUE TITLE
[BUG]: Incorrect particle behavior when timescale is above 100%

### ISSUE THREAD

**Issue by Cubature1** [yogwoggf/gelly#38]
### GPU

RTX 3050

### Operating System

Win 11

### Is this specific to performance?

- [ ] Yes
- [X] No

### Issue Type

None

### Incident Description

When the Gelly timescale is set above 100% (As in 1/10th of the default), particles behave improperly. Friction does not exist, and adhesion does not function properly. Seems to fix the other issues on the 1.3.0 version to an extent as well.

**Comment by yogwoggf** [comment]
This is because FleX naturally assumes a 1/60th timestep, what 100% does is multiply 1/60 by one, which equals itself. However, you'll notice that everything is *slow*. But, at the same time, if you increase gravity to match source, eventually the constraint solver in the physics engine exhibits mass instability and glitches.

This is an issue with no clear solution in sight yet, sorry. I'll keep it open in case I figure new things out

**Comment by Derpius** [comment]
> if you increase gravity to match source, eventually the constraint solver in the physics engine exhibits mass instability and glitches.

Is this because the raw numbers are just too big for what it expects? Can you not translate hammer units to metric when you write to the solver, and back again when you read? (I suggested this ages ago)

**Comment by yogwoggf** [comment]
Superseded by the ticket #53
